[package]
name = "anchor_addrx"
version = "1.0.0"
authors = []
upgrade_policy = "compatible"

[addresses]
anchor_addrx = "0xea7fb3f7cf8efcd569529520f6c7fe691c34658320b7cacc869b6a33551c6b07"


[dev-addresses]


[dependencies.CedraFramework]
git = "https://github.com/cedra-labs/cedra-framework.git"
rev = "main"
subdir = "cedra-framework"
[dev-dependencies]
